### ISSUE TITLE
CMS VM Delete and Terminate not working.

### ISSUE THREAD

**Issue by aporlowski** [cloudmesh/cloudmesh-azure#6]
After updating the Azure Provider to use the new SDK, I noticed that `cms vm terminate` and `cms vm delete` are not working. I am not sure if they were working prior to updates. Below is an error message I recieve when trying to terminate an Azure VM.

> vm terminate benchmark-3
INFO: Deleting Azure Virtual Machine
'VirtualMachinesOperations' object has no attribute 'delete'
Traceback (most recent call last):
  File "/home/anthony/cm/cloudmesh-cmd5/cloudmesh/shell/shell.py", line 419, in onecmd
    return func(arg)
  File "/home/anthony/cm/cloudmesh-cmd5/cloudmesh/shell/command.py", line 115, in new
    func(instance, args, arguments)
  File "/home/anthony/cm/cloudmesh-cloud/cloudmesh/vm/command/vm.py", line 580, in do_vm
    vms = provider.destroy(name)
  File "/home/anthony/cm/cloudmesh-admin/cloudmesh/mongo/DataBaseDecorator.py", line 87, in wrapper
    current = f(*args, **kwargs)
  File "/home/anthony/cm/cloudmesh-cloud/cloudmesh/compute/vm/Provider.py", line 88, in destroy
    return self.loop_name(name, self.p.destroy)
  File "/home/anthony/cm/cloudmesh-cloud/cloudmesh/compute/vm/Provider.py", line 94, in loop_name
    vm = func(name=name, **kwargs)
  File "/home/anthony/cm/cloudmesh-azure/cloudmesh/azure/compute/Provider.py", line 1564, in destroy
    del_vm = self.vms.delete(self.GROUP_NAME, vm['name'])
AttributeError: 'VirtualMachinesOperations' object has no attribute 'delete'

**Comment by laszewsk** [comment]
Gregor von Laszewski i think its called deallocate and no longer delete
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.compute import ComputeManagementClient, ComputeManagementClientConfiguration
credentials = ServicePrincipalCredentials(
    client_id = '<client-id>',
    secret = '<key>',
    tenant = '<tenant-id>'
)
subscription_id = '<subscription-id>'
compute_config = ComputeManagementClientConfiguration(credentials, subscription_id, api_version='2015-05-01-preview')
compute_client = ComputeManagementClient(compute_config)
resource_group_name = '<resource-group>'
vm_name = '<vm-name>'
result = compute_client.virtual_machines.deallocate(resource_group_name, vm_name)
the api version needs to ba adapted based on what we use
3:15 PM
this is from the tech preview of the library some years back. not sure if it has changed.
alternatively we coudl do the rest call via pyton requests
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/delete

docs.microsoft.comdocs.microsoft.com
Virtual Machines - Delete (Azure Compute)
The operation to delete a virtual machine.
